### ISSUE TITLE
Server project shows warning on mvn spring-boot:run

### ISSUE THREAD

**Issue by gunjank** [souravbh/mockProxyServer#2]
mymachine:mockProxyServer someuser$ `mvn spring-boot:run`
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.bh.gateway:mockProxyServer:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for org.docx4j:docx4j:jar should not point at files `within the project directory, ${basedir}/lib/docx4j-6.0.1.jar will be unresolvable by dependent projects @ line 33, column 16`
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
`[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.`
[WARNING]

**Comment by souravbh** [comment]
The warn is coming of direct inclusion of the docx4j from lib in Pom. The jar was compiled locally and included in the project.I will replace with the maven central repo version in docx4j in the Pom. Since right now the server is not being extended by any other module, this will be tagged as lower priority and will be fixed shortly.

**Comment by souravbh** [comment]
Updated the reference of doc4j from central maven repo..
